/**
 * Connections — larger neural-network visualization with an explanation
 * side panel. Phase 1 = visual prototype only.
 */
import { Info, Share2 } from "lucide-react";
import { NeuralGraph } from "@/components/NeuralGraph";
import { Panel, SectionHead, TermWindow, Chip } from "@/components/terminal";
import { GRAPH_NODES, GRAPH_EDGES } from "@/config/graph-data";

export default function Connections() {
  return (
    <div className="rise space-y-5">
      <SectionHead
        title="Connections"
        sub="how your memories relate — currently a visual prototype"
        icon={Share2}
        count={GRAPH_EDGES.length}
      />

      <div className="grid gap-4 lg:grid-cols-3">
        {/* Graph */}
        <div className="lg:col-span-2">
          <TermWindow title="neural_map_full.json — knowledge graph" className="h-full">
            <div className="p-3 sm:p-4">
              <NeuralGraph
                nodes={GRAPH_NODES}
                edges={GRAPH_EDGES}
                variant="page"
                className="term-dots rounded border border-border/60 bg-secondary/30 p-2"
              />
            </div>
          </TermWindow>
        </div>

        {/* Side panel */}
        <div className="space-y-4">
          <Panel className="p-4">
            <div className="flex items-center gap-2">
              <Info className="size-4 text-primary" />
              <h3 className="text-sm font-semibold">What am I looking at?</h3>
            </div>
            <p className="mt-2.5 text-sm leading-relaxed text-muted-foreground">
              Connections represent relationships between information in your
              second brain. When two memories share meaning, a link forms —
              and over time those links become a map of how you think.
            </p>
            <div className="mt-3 rounded border border-amber-term/40 bg-amber-term/10 p-2.5 text-xs leading-relaxed text-amber-strong">
              <span className="font-semibold uppercase tracking-wider">Phase 1 note:</span>{" "}
              the graph above is a hand-authored visual demo. AI-generated
              connections arrive in a later phase.
            </div>
          </Panel>

          <Panel className="p-4">
            <h3 className="text-sm font-semibold">Legend</h3>
            <ul className="mt-2.5 space-y-2 text-xs text-muted-foreground">
              <li className="flex items-center gap-2">
                <span className="size-2 rounded-full bg-[#166534]" />
                AI — your machine-learning cluster
              </li>
              <li className="flex items-center gap-2">
                <span className="size-2 rounded-full bg-[#155e75]" />
                Programming — tools and systems
              </li>
              <li className="flex items-center gap-2">
                <span className="size-2 rounded-full bg-[#8a4b08]" />
                Business — product and ventures
              </li>
              <li className="flex items-center gap-2">
                <span className="size-2 rounded-full bg-[#5b21b6]" />
                Education — learning systems
              </li>
              <li className="flex items-center gap-2">
                <span className="size-2 rounded-full bg-[#9f1239]" />
                Science — how minds work
              </li>
            </ul>
            <p className="mt-3 border-t border-border/60 pt-2.5 text-[10px] uppercase tracking-widest text-muted-foreground/70">
              hover nodes to trace their links
            </p>
          </Panel>

          <Panel className="p-4">
            <h3 className="text-sm font-semibold">Stats</h3>
            <dl className="mt-2.5 space-y-1.5 text-xs">
              <div className="flex justify-between">
                <dt className="text-muted-foreground">nodes</dt>
                <dd className="font-semibold tabular-nums">{GRAPH_NODES.length}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">edges</dt>
                <dd className="font-semibold tabular-nums">{GRAPH_EDGES.length}</dd>
              </div>
              <div className="flex justify-between">
                <dt className="text-muted-foreground">generated by</dt>
                <dd>
                  <Chip tone="amber">demo data</Chip>
                </dd>
              </div>
            </dl>
          </Panel>
        </div>
      </div>
    </div>
  );
}
